export const returnMessages = Object.freeze({
  UserNotCreated: 'Something went wrong! User is not created!',
  UserNotFound: 'User not found!',
  UserCodeNotFound: 'Code not found!',
  CodeNotValid: 'Code is not valid!',
  UserSuccessfullyLoggedIn: 'You have been successfully logged in!',
  EmailInUse: 'Email is in use!',
  EmailPasswordValidation: 'Invalid password or email!',
  EmailNotVerified: 'Email is not verified!',
  WorkoutNameLength: 'workoutName must be between 1 and 255 characters!',
  WorkoutNotFound: 'Workout not found!',
  WorkoutOwnerInvite: 'Only workout owners can invite users!',
  TokenNotValid: 'Token is not valid!',
  TokenIsValid: 'Token is valid!',
  LimitReached: 'Limit reached!',
  BadUserCode: 'Bad Code!',
});